import React from 'react'

export default function Home() {
  return (
    <div>
        <h1>home</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur quisquam dolores nemo voluptatum, adipisci eius alias, accusantium enim quia dolorum rerum deserunt vitae culpa repellat ipsum dolor, tenetur labore esse facere corporis molestiae officiis dolorem ipsam exercitationem. Numquam consequuntur eaque quasi illo atque recusandae quaerat ex ab architecto delectus labore vero quae nulla voluptatem mollitia dolor possimus modi inventore, ipsam quam obcaecati soluta dolores quod libero. Minus blanditiis laudantium corrupti sint perferendis earum vero mollitia reprehenderit, non, temporibus nisi labore quaerat soluta fugit repellat. Nesciunt totam, voluptatibus reprehenderit quibusdam nihil labore ab eaque molestias nam eius quod cum, dolorem quidem velit dolores, delectus id accusamus aliquid aspernatur minima mollitia. In reiciendis veritatis cum distinctio repellendus est aliquid amet animi tempore eveniet autem quas eligendi tenetur asperiores odit iste, possimus hic sint ipsam. Eum, possimus quibusdam! Laboriosam suscipit nisi corporis, magnam ea amet quam consequatur dignissimos voluptate delectus temporibus aspernatur iure soluta dolorem. Dolores quas autem omnis, ipsum cum aspernatur doloremque a labore facilis quae tempora pariatur quo nulla obcaecati similique provident temporibus explicabo eius! Sit voluptatibus fuga animi. Nemo odio dicta asperiores, perferendis, animi quis adipisci cupiditate placeat libero voluptatum tempore dolore consequatur dolorem, at sed assumenda modi. Quaerat inventore sed sequi voluptate, laborum, quod repellat repellendus laboriosam nemo magnam eveniet alias illo illum assumenda perspiciatis animi nam odio odit nesciunt rem in fugit voluptatem. Sed corrupti cupiditate illo! Accusantium, earum modi pariatur blanditiis velit dolorem sapiente, dolores doloribus, ullam aliquid id totam autem ducimus officia ipsam? Quae repudiandae vitae impedit, veniam dolorem, blanditiis ipsa quis porro corporis maiores officia amet. Maiores quo rem voluptatum sit facere quisquam saepe laudantium labore hic placeat suscipit accusamus, pariatur ea nesciunt? Aperiam aut quaerat laborum placeat aliquam provident reiciendis quisquam beatae, deleniti ullam quo numquam quia officiis impedit esse? Amet reprehenderit ducimus temporibus!</p>
    </div>
  )
}
